name: Release Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Development Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          pip install --disable-pip-version-check -r mkdocs_requirements.txt

      - name: Configure Git
        run: |
          git config --local user.name $GITHUB_ACTOR
          echo $GITHUB_ACTOR

      - name: mike Deploy Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DOMAIN: github.hpe.com
        run: |
          mike deploy --push dev
