name: Release Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Development Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          pip install --disable-pip-version-check -r mkdocs_requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"

      - name: mike Deploy Main
        env:
          GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
        run: |
          mike deploy --push dev
